ci(default-bare): decrease ansible verbosity to v

diff --git a/.github/workflows/default-bare.yml b/.github/workflows/default-bare.yml
--- a/.github/workflows/default-bare.yml
+++ b/.github/workflows/default-bare.yml
@@ -55,14 +55,14 @@ jobs:
         if: ${{ matrix.os != 'windows-latest'}}
       - name: run test
         run: |
-          cd $GITHUB_WORKSPACE/juju4.chrome_config && ansible-playbook -i localhost, --connection=local --become -vv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS}
+          cd $GITHUB_WORKSPACE/juju4.chrome_config && ansible-playbook -i localhost, --connection=local --become -v test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS}
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
         if: ${{ matrix.os != 'windows-latest'}}
       - name: idempotency run
         run: |
-          cd $GITHUB_WORKSPACE/juju4.chrome_config && ansible-playbook -i localhost, --connection=local --become -vv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
+          cd $GITHUB_WORKSPACE/juju4.chrome_config && ansible-playbook -i localhost, --connection=local --become -v test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
         if: ${{ matrix.os != 'windows-latest'}}
       - name: On failure
         run: |
